"""Authored classroom stories. Run this to refresh weeks.json, then build_lessons.py.

The seven strings for each concept are: analogy, three concrete mappings,
where the analogy breaks, worked micro-example, learner question, answer,
and a plausible wrong claim. All examples are synthetic teaching cases.
"""
import json
from pathlib import Path
R=Path(__file__).resolve().parent

def C(analogy,mapping,limit,worked,question,answer,wrong):
    parts=[x.split(' = ',1) for x in mapping.split('; ')]
    assert len(parts)==3 and all(len(x)==2 for x in parts),mapping
    return dict(analogy=analogy,mapping=parts,limit=limit,worked=worked,question=question,answer=answer,wrong=wrong)
W={}
W[1]=dict(story='The late-bus refund',hook='A confident assistant says a late bus ticket is reimbursed. Policy P1 says student travel is not reimbursed. Would you trust the answer?',memory='A polished reply is a draft; trace its claim back to P1.',transfer='The assistant repeats the answer twice, but one version invents an exception. Which answer belongs in the ten-case baseline?',concepts=[
 C('A weather forecast predicts a category; a novelist writes a fresh sentence.','Forecast label = predicted class; New sentence = generated sequence; Weather record = training examples','A generative model also predicts the next token internally; the distinction concerns the output task.','Given “Is travel reimbursed?”, a classifier could output NO; a generator could write “No, under P1.”','Can a newly worded answer still be false?','Yes. Novel wording does not establish factual support.','Every generated sentence is creative evidence.'),
 C('A cook proposes a dish; the restaurant checks ingredients and allergies before serving.','Cook = model; Ingredient sheet = policy P1; Server check = application validation','A restaurant check is a deliberate rule; a model does not automatically enforce permissions.','The model proposes “Yes”; the application compares the claim with P1 and flags it.','Which component can stop an unsupported answer reaching the student?','The application check using P1 can flag or block it.','The model itself guarantees the college rule.'),
 C('A librarian needs both the question and the correct shelf card.','Request = task prompt; Shelf card = supplied context P1; Draft reply = model output','The shelf card helps only if it is relevant, current and actually used.','“Answer using P1 and cite it” includes a task and source; “help me” does not.','What should the prompt say when P1 lacks the answer?','State that the assistant should say evidence is missing.','Longer prompts always create true answers.'),
 C('A teacher marks ten scripts against one answer key, then repeats two questions.','Answer key = manual baseline; Script = model reply; Repeat = variability check','One short sample cannot estimate performance in all future situations.','Seven of ten replies are supported: 7/10 = 70%; log the three failures and two repeats.','Why record the denominator and repeats?','The denominator shows sample size; repeats show whether outputs change.','A 70% score means the next answer is certainly correct.')])
W[2]=dict(story='The icon studio',hook='A designer wants varied icons that resemble a style without copying one example. How could two training ideas approach this?',memory='VAE: compress and reconstruct. GAN: propose and critique.',transfer='The generated icon looks sharp but repeats one shape. Which additional check would reveal lack of diversity?',concepts=[
 C('A travel suitcase packs the essential features and unpacks them at the destination.','Packing = encoder; Compact code = sampled latent z; Unpacking = decoder','A VAE learns a distribution and reconstruction objective; a suitcase is not a probabilistic model.','A 2-value icon [0.2, 0.8] enters an encoder; a sampled z is decoded into a reconstructed icon.','Which arrow could lose a fine detail?','Compression into z can discard information; compare original and reconstruction.','A VAE stores and copies exact training icons.'),
 C('A map places similar destinations near one another.','Map point = latent coordinate; Nearby points = related codes; Visit = decoded output','Closeness in a toy plot does not guarantee human-perceived similarity.','Change toy z from 0.3 to 0.7; compare the output pattern while keeping the decoder fixed.','Does a smoother output prove realism?','No. Inspect examples and use a suitable quality test.','A latent coordinate is a pixel location.'),
 C('A forger and examiner improve through repeated feedback.','Forger = generator; Examiner = discriminator; Critique = training signal','The analogy can imply a human examiner; the discriminator is a learned network and may be fooled.','A generator proposes an icon; the discriminator scores real versus generated examples; both update.','Which part produces the new image?','The generator produces it; the discriminator provides a training signal.','The discriminator paints the final image.'),
 C('A student gets better on practice sheets while worse on unfamiliar exam sheets.','Practice curve = training loss; Unseen sheet = validation set; Visual inspection = quality check','GAN losses are not simple universal quality scores; compare held-out samples too.','Training error 0.30→0.18→0.12; validation 0.32→0.20→0.26. Inspect epoch 3.','Why is the final training number insufficient?','Validation worsened; quality and variety require separate inspection.','Lower training loss always proves better new icons.')])
W[3]=dict(story='The consent-safe poster',hook='A team requests a synthetic poster. The output looks vivid but may show a recognisable person. How do generation and review interact?',memory='Noise becomes an image through repeated learned denoising; check consent and details.',transfer='A poster has readable-looking text that spells the event date incorrectly. Which check catches the error?',concepts=[
 C('A photograph becomes harder to see as fog builds in small steps.','Clear image = training example; Added fog = forward noise; Fog level = time step','Noise is mathematically sampled; real fog is not the model’s training process.','At low noise the L-shaped grid remains visible; at high noise most cells are obscured.','Which direction is used while preparing training pairs?','Forward: progressively add noise to a clean example.','The model learns by removing noise before any noise is added.'),
 C('A restorer removes a little fog at a time after learning from many examples.','Cloudy view = noisy sample; Estimated fog = model prediction; Clearer view = next step','A real model does not secretly have the exact clean target at generation time.','The prepared notebook’s toy restorer uses a clean target to illustrate steps; label that shortcut.','What extra information makes the toy restoration easier?','It has access to the original clean grid.','The toy denoiser proves real model image quality.'),
 C('A poster brief steers an artist, but leaves room for choices.','Brief = text condition; Artist decisions = denoising path; Draft poster = output','The brief does not guarantee that every requested detail appears correctly.','Use “blue campus poster” for both trials; compare date lettering and layout separately.','What stays fixed in a fair output comparison?','Keep the brief and checklist fixed; record changed generation settings.','A detailed prompt guarantees exact text in images.'),
 C('A print editor checks a draft before it reaches the public.','Draft = generated image; Release form = consent check; Proofread = image detail check','A release form cannot be inferred from pixels; ask for documented permission.','The poster is attractive, but a face resembles a classmate and the date is wrong: hold publication.','What two reasons justify holding this image?','Consent is unresolved and the date detail is incorrect.','A synthetic image needs no rights or quality review.')])
W[4]=dict(story='The confusing sentence',hook='In “Ava told Bea that she won,” which earlier word does “she” refer to? A model must use context, yet ambiguity can remain.',memory='Tokenise, score visible context, and choose the model role for reading or writing.',transfer='A drafting decoder has the next word hidden. What happens to that column in its attention grid?',concepts=[
 C('A sentence is cut into tiles before a game reads it.','Sentence = input string; Tiles = tokens; Tile numbers = IDs','Token pieces need not be complete words; the vocabulary is model-specific.','“unbelievable” might be one piece or several; record the tokenizer used before counting.','Why can word count differ from token count?','A tokenizer may split a word into several pieces.','One word always equals one token.'),
 C('A reader highlights earlier words that matter to the current word.','Current word = query; Highlight strength = attention weight; Notes = weighted context','Attention weights alone are not a complete explanation of model decisions.','Scores [1,2,0] yield about [0.245,0.665,0.090]; the middle token gets most weight.','Do weights identify a proven causal explanation?','No. They show one computation, not the whole model’s reason.','The largest attention cell proves the final answer.'),
 C('An exam candidate may consult earlier pages, not tomorrow’s answer sheet.','Earlier page = past token; Covered page = masked future token; Allowed view = causal context','A mask is an enforced attention constraint; it does not ensure factual accuracy.','Mask the third of three scores [1,2,0]; renormalised weights are about [0.269,0.731,0].','What happens to the forbidden position?','Its weight is zero; visible positions are renormalised.','Masking deletes a token from the vocabulary.'),
 C('A reader, a writer, and a reader-writer have different jobs.','Reader = encoder; Writer = decoder; Read and write = encoder–decoder','Many current systems combine components; this is a useful role sketch, not a full taxonomy.','Classify a sentence: encoder. Continue it: decoder. Translate it: encoder–decoder.','Which role suits translation in this simplified comparison?','An encoder reads source text and a decoder writes target text.','An encoder always generates the final long reply.')])
W[5]=dict(story='The missing invoice total',hook='An invoice has quantity 3 and price €12, but no printed total. Should the assistant fill €36 into the extracted total field?',memory='Specify the task, keep missing fields missing, then check structure and source.',transfer='A syntactically valid JSON reply lists total €36. Which two checks disagree?',concepts=[
 C('A precise work order names each item and what to do if it is absent.','Work order = prompt; Required items = fields; Missing-item rule = null instruction','A prompt guides behaviour but does not enforce correctness by itself.','Request invoice_id and listed_total; say “use null if the total is not printed.”','What should the output contain for this invoice’s listed total?','null, because no printed total appears.','The assistant should infer every blank value.'),
 C('A clerk points to the exact line on a receipt before copying it.','Receipt line = source evidence; Copied value = extracted field; Pointer = source span','A source pointer may still point to the wrong line; verify the match.','Quantity 3 and unit price €12 are visible. €36 is a calculation, not a printed total.','Can €36 be labelled “extracted listed total”?','No. It can be a separate calculated check only.','A plausible calculation counts as document evidence.'),
 C('A shipping form checks boxes and value types before accepting a parcel.','Boxes = field names; Type rule = schema; Reject stamp = validator flag','A correct shape does not prove the value came from the document.','An ID of INV-04 and a listed total of €36 can pass type checks but fail a source check.','Which test detects a wrong but well-typed amount?','Compare the returned amount with the original invoice text.','Valid JSON means the facts are valid.'),
 C('A careful witness says “I did not see that number.”','Unseen figure = missing field; Honest reply = null; Follow-up = human review','Abstention can be too cautious; measure missing and falsely missing fields.','When the total is absent, the validator flags null for review without inventing a figure.','Why preserve a missing value?','It separates unknown source content from an independent calculation.','Every missing field is a model failure to be hidden.')])
W[6]=dict(story='The library-renewal search',hook='A learner asks “Can I renew my book?” Policy P2 says “library loans may be extended once.” Which passage should search find?',memory='Split with source IDs, compare retrieval methods, and filter permissions first.',transfer='A staff-only policy has a perfect keyword match. Should the student see it?',concepts=[
 C('A long textbook gets labelled index cards for individual sections.','Book section = passage chunk; Card label = source ID; Edition = version','Cutting at arbitrary length can separate a condition from its rule.','P2 becomes a short passage with ID P2 and version; keep “once” in the same passage.','Why preserve the source ID and version?','They let a learner verify the answer in the correct policy edition.','A chunk needs only its text.'),
 C('An index finds pages that contain the exact words you entered.','Search phrase = query tokens; Word matches = overlap score; Top cards = ranked passages','Synonyms can make a relevant passage score poorly.','“renew” does not exactly match P2’s “extend”; a keyword-only search may miss it.','What explains this miss?','Different words express a similar intent.','No exact match proves no relevant policy exists.'),
 C('A map places related meanings near one another.','Question = numeric embedding; Policy = numeric embedding; Distance = similarity','Similar vectors can retrieve the wrong passage; check text and permissions.','Toy vectors q=[1,0], P2=[1,1], P3=[0,1]: cosine scores about .707 and 0.','Which passage ranks nearer to q in this toy calculation?','P2, with the larger cosine similarity.','An embedding is an authoritative answer.'),
 C('A library card allows entry to some shelves but not staff cabinets.','Student role = access identity; Open shelf = allowed policy; Cabinet = restricted source','Filtering after generation may leak details already inserted into context.','Filter staff-only P5 before ranking; never supply it to the student answer stage.','When must the access filter apply?','Before retrieval results are passed into an answer.','A relevant staff policy may be shown if cited.')])
W[7]=dict(story='The cited deadline answer',hook='The assistant cites P3 for “two extensions,” but P3 permits one. A citation is present. Is the answer supported?',memory='Retrieve, answer, check each claim, and abstain without evidence.',transfer='A fresh question asks about a rule absent from all five policies. What should the assistant do?',concepts=[
 C('An open-book examiner finds the page before writing the answer.','Question = query; Open page = retrieved passage; Answer = cited reply','Retrieval can pick an irrelevant page; answer quality depends on what was found.','P3 states one extension in seven days; answer “one [P3]” after retrieving P3.','Which step happens before drafting?','Find the relevant allowed passage.','A citation added afterward repairs a false answer.'),
 C('A footnote is useful only when its source actually says the claim.','Sentence = claim; Footnote = source ID; Highlight = supporting span','Checking entailment can involve nuance; use a human for disputed cases.','“Two extensions [P3]” is unsupported because P3 says one, even though the ID exists.','What must be checked beyond the presence of a citation?','The passage must support the exact claim.','Any source ID proves the sentence.'),
 C('A careful researcher leaves a blank when the archive lacks evidence.','Missing page = no relevant passage; Blank = abstain; Search log = reason','A retrieval miss may hide a real answer elsewhere; report the search limit.','Ask about parking permits; none of five policies covers it, so say evidence is unavailable.','What should the system say?','It lacks a relevant approved source in this corpus.','The model should guess from common knowledge.'),
 C('A practice quiz guides choices; an unopened exam checks the choice.','20 questions = development set; Search setting = chosen configuration; 10 new questions = final check','Ten final cases are still a small sample; report each failure and denominator.','Compare top-k 1 and 2 on 20 practice questions, freeze the choice, then open ten final cases.','Why not tune again after seeing the ten final answers?','That would contaminate the independent check.','Reusing final questions improves an unbiased estimate.')])
W[8]=dict(story='The reimbursement cap tool',hook='A €55 claim has a €40 cap. The assistant may calculate the payable amount. A separate request asks it to change the cap. Which path needs approval?',memory='Validate a read-only tool; route write actions through human approval.',transfer='A tool receives amount −€5. What should happen before any calculation?',concepts=[
 C('A calculator performs one defined operation when given a valid number.','Number = tool argument; Guard = input validator; Display = tool result','The model may choose the wrong tool or arguments; inspect the call.','cap(55,40) returns €40; cap(−5,40) is rejected as invalid input.','What should run before the arithmetic?','Type and range validation.','A tool call is safe because its function is simple.'),
 C('An assembly line follows the same stations in a fixed order.','Station = code step; Conveyor = workflow; Finished item = checked result','Real workflows can branch on validated conditions, while remaining predefined.','Validate amount → calculate cap → format reply; a negative amount stops at validation.','Who chooses the next station in this version?','The predefined workflow code.','A workflow must involve a free-form agent.'),
 C('A dispatcher selects among allowed services to handle a request.','Dispatcher = model decision; Service desk = tool interface; Ticket = logged result','Agent choice is bounded by available tools and permissions; autonomy is limited.','The model proposes calculator; the interface validates €55 before executing it.','Can the model authorize a write by choosing a tool?','No. Authorization is enforced outside the model.','An agent can grant itself a new permission.'),
 C('A bank transfer waits for an authorized person to approve it.','Transfer request = write action; Approver = authorized reviewer; Receipt = audit record','Some read-only actions also need controls when they reveal restricted information.','Changing the cap requires an approval record; calculation of €40 does not change the record.','What evidence shows a write was authorized?','An approval tied to the request and recorded action.','A polite request is enough approval.')])
W[9]=dict(story='The revised policy problem',hook='Practice results say a tuned model wins 9/10, but a revised policy arrived yesterday and final cases show 6/10. What should change first?',memory='Diagnose the failure, choose prompt or RAG or tuning, and test fresh cases.',transfer='The system returns the right fact but the wrong JSON field names. Which adaptation is the simplest first trial?',concepts=[
 C('A clearer recipe can change a cook’s output without retraining the cook.','Recipe = prompt; Example plate = few-shot example; Taste check = task evaluation','Instructions can fail; a prompt does not update facts or guarantee conformance.','On ten practice cases, a clarified prompt improves 6/10 to 8/10; record the cases.','When is this an inexpensive first trial?','When the failure concerns task instructions or format.','A prompt can permanently teach yesterday’s revised policy.'),
 C('A clerk opens the current rulebook instead of relying on memory.','Rulebook = updated policy; Page search = retrieval; Quoted line = grounded answer','Retrieved text still needs access, relevance and claim checks.','Replace P3 with its approved revised version, reindex and retrieve it for the question.','Where should a changed policy be updated first?','In the authoritative document and retrieval index.','Retrieval changes model weights.'),
 C('A musician practises many examples to change a habit.','Practice pieces = labelled data; Habit change = weight update; New concert = final test','Small practice gains can reflect overfitting; tuning is not a live fact store.','Base 6/10, prompted 8/10, tuned 9/10 in practice; final tuned 6/10. Investigate.','Does the practice result prove tuning should ship?','No; the fresh test and failure analysis matter.','Fine-tuning is guaranteed to beat a good prompt.'),
 C('A small adapter changes a machine’s behaviour without replacing its engine.','Engine = frozen base weights; Adapter = low-rank matrices; New behaviour = tuned output','Low trainable parameter count does not remove data, compute or evaluation needs.','LoRA trains small matrices while freezing most base weights; no live tuning is required in this lab.','What does LoRA reduce?','The trainable parameter count compared with full fine-tuning.','LoRA retrieves current policy documents automatically.')])
W[10]=dict(story='The €54 invoice',hook='An invoice image lists two items at €20 and €5 tax, yet displays €54 total. A model reads €54 correctly. Should the payment pass?',memory='Read the source, preserve field pointers, calculate independently, and flag discrepancies.',transfer='A blurred invoice number looks like INV-08 or INV-03. Which field should be marked uncertain?',concepts=[
 C('A person can read a photo and a text note together.','Photo = visual input; Reader = OCR or vision step; Typed note = transcribed text','This notebook uses a prepared transcription; it does not run OCR or test a vision model.','The prepared text records quantity 2, unit price €20, tax €5 and listed total €54.','What capability is represented by the supplied transcription?','An upstream reading step, whose accuracy still needs checking.','The notebook itself recognises image pixels.'),
 C('An auditor writes the page and line beside every copied number.','Printed number = visible field; Copied value = extraction; Page pointer = source location','A pointer can be wrong or ambiguous, especially with poor image quality.','Record “listed_total = €54” with the invoice field location; keep calculation separate.','What does a source pointer let another person do?','Find and verify the value in the original document.','A correctly formatted field proves its source.'),
 C('A cashier recomputes a bill instead of trusting the printed sum.','Items = 2 × €20; Tax = €5; Independent sum = €45','Real invoices may have discounts and other rules; specify the case assumptions.','2 × €20 + €5 = €45; listed total €54, a €9 discrepancy.','Does reading €54 correctly make it a correct payable total?','No. The independent arithmetic disagrees by €9.','Accurate OCR implies accurate arithmetic.'),
 C('A reviewer marks an unreadable receipt field with a question mark.','Blurred area = uncertain observation; Question mark = review flag; Second look = verification','Uncertainty needs a clear workflow; marking everything uncertain is unhelpful.','If INV-08/INV-03 cannot be distinguished, store an uncertain ID and request review.','What would be unsafe to store?','A guessed invoice ID presented as certain.','A plausible guess should be saved silently.')])
W[11]=dict(story='The failed classroom release',hook='Version 2 answers faster but exposes one staff-only policy to a student. Would you release it?',memory='A required access test blocks release; keep safe traces and a tested rollback.',transfer='The new version passes answer checks but fails the missing-source test. What does the release gate decide?',concepts=[
 C('An aircraft checklist must pass every required item before departure.','Candidate version = aircraft; Required tests = checklist; Release = departure decision','A checklist reduces known risk; it cannot prove zero future failures.','Candidate v2 fails staff access, so the release decision is “block” even if other scores improve.','Can a faster answer override a failed access gate?','No. The required access test must pass.','Most tests passing is enough to release.'),
 C('A shipping receipt records what happened without copying the private parcel.','Event = trace record; Private text = removed content; Receipt = filtered log','Aggressive filtering can hide useful debug details; keep safe IDs and event type.','Log request ID, role, policy ID and outcome; omit student question text and secret key.','Which fields help investigate without exposing private text?','Safe identifiers, role, source ID and decision.','A useful trace must store the full private prompt.'),
 C('A theater switches back to the last working lighting cue.','New cue = candidate version; Old cue = tested configuration; Switch = rollback','Rollback needs tested artifacts and compatible data; rehearsal matters.','After v2 leaks P5, restore v1 with its policy index and confirm the student test passes.','What must be checked after restoring v1?','Re-run the critical access and answer checks.','Rollback means changing only the visible version label.'),
 C('A restaurant compares the full meal bill with meals actually served.','Full bill = total run cost; Served meals = successful answers; Unit cost = cost per success','A very small sample can make the estimate noisy; state the denominator.','If ten runs cost €0.20 and eight meet criteria, cost per success = €0.025.','Why divide by eight rather than ten?','Only eight runs delivered the defined successful outcome.','Cheapest run is automatically best delivery.')])
W[12]=dict(story='The fresh policy question',hook='A student appeals on day 12. P4 says appeals must be filed within ten days. The team must answer, cite, test and explain a fresh failure.',memory='Show the question-to-evidence path, your measured change and a repeatable handover.',transfer='A new policy edition changes the appeal window. What records, index and tests need updating?',concepts=[
 C('A museum guide checks which rooms a visitor may enter before quoting a label.','Visitor role = access check; Exhibit label = retrieved P4; Guided answer = cited response','A citation needs to support the exact statement and the version in force.','For day 12 under the supplied ten-day P4, answer no and cite P4 with the used version.','Which three checks precede a confident reply?','Allowed source, relevant passage and supported claim.','An answer is valid because it includes [P4].'),
 C('A science notebook shows a changed setting, observation and explanation.','Setting change = your code change; Measurement = experiment table; Reason = individual explanation','A before/after result in one toy case cannot establish general reliability.','Show baseline, chosen setting, case counts and one error that still remains.','What proves the work is yours and reproducible?','The changed code, settings, inputs and explanation.','A polished demonstration alone proves understanding.'),
 C('A mechanic diagnoses a new symptom by testing the failing part.','Symptom = new failure; Component = likely layer; Check = targeted test','Some failures cross layers; record uncertainty and test competing causes.','If P4 is retrieved but the answer says 12 days is allowed, test claim support before changing search.','Which layer deserves the first test here?','Answer support using the retrieved P4 passage.','Every wrong answer is a retrieval failure.'),
 C('A relief teacher can run a lesson from a clear folder and known limits.','Folder = setup guide; Known gaps = limitations; Trial run = repeatable handover','Documentation can go stale; date versions and rerun the checks.','Give installation steps, source versions, test commands, role rules and rollback instructions.','What can the next maintainer reproduce?','The setup, evaluation and known-failure checks from the handover.','The notebook is self-explanatory without instructions.')])
assert len(W)==12 and all(len(v['concepts'])==4 for v in W.values())
(R/'weeks.json').write_text(json.dumps(W,indent=2,ensure_ascii=False),encoding='utf-8')
print('Authored',len(W),'weeks and',sum(len(v['concepts']) for v in W.values()),'concept stories')
